from .core import ThreePlusOneMLP, FitResult, EpochRecord, centered_singleton_seed
from .datasets import xnor
from .experiments import epsilon_sweep
from .geometry import (
    TETRAHEDRAL_BRANCH_ANGLE,
    centered_contrast_vertices,
    child_axes,
    dual_tetrahedra,
    oriented_area,
    tetrahedral_relative_order,
    tetrahedron_vertices,
)
from .dynamics import (
    DualRotorParams,
    DualRotorState,
    relative_energy,
    relative_regime,
    relative_winding,
    simulate_dual_rotor,
    total_momentum,
)
from .selection import (
    NextOneParams,
    NextOneState,
    branch_lock_error,
    branch_phase,
    branch_rhs,
    c3_rotate,
    energy_dissipation_rate,
    growth_rate,
    rotor_energy,
    selected_branch,
    simulate_next_one,
)
from .transverse import (
    TransverseEpochRecord,
    add_transverse_seed,
    epoch_transverse_matrix,
    sample_transverse_matrix,
    scan_transverse_growth,
    singular_values,
    transverse_residual,
    transverse_residual_norm,
)

__all__ = [
    "ThreePlusOneMLP",
    "FitResult",
    "EpochRecord",
    "centered_singleton_seed",
    "xnor",
    "epsilon_sweep",
    "TETRAHEDRAL_BRANCH_ANGLE",
    "centered_contrast_vertices",
    "child_axes",
    "dual_tetrahedra",
    "oriented_area",
    "tetrahedral_relative_order",
    "tetrahedron_vertices",
    "DualRotorParams",
    "DualRotorState",
    "relative_energy",
    "relative_regime",
    "relative_winding",
    "simulate_dual_rotor",
    "total_momentum",
    "NextOneParams",
    "NextOneState",
    "branch_lock_error",
    "branch_phase",
    "branch_rhs",
    "c3_rotate",
    "energy_dissipation_rate",
    "growth_rate",
    "rotor_energy",
    "selected_branch",
    "simulate_next_one",
    "TransverseEpochRecord",
    "add_transverse_seed",
    "epoch_transverse_matrix",
    "sample_transverse_matrix",
    "scan_transverse_growth",
    "singular_values",
    "transverse_residual",
    "transverse_residual_norm",
]
__version__ = "0.4.0"
